name: react-native-android-build-apk
on:
  push:
    branches:
      - main
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          apt install tree
          tree
          npm ci
          # npm test
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm ci
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
          apt install tree
          cd app
          tree
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: pokeApp.apk
          path: cd android/app/build/outputs/apk/release/
  release-androisd:
    needs: build-android
    runs-on: ubuntu-latest
    steps: 
      - name: "Release"
        run: |
          echo "Release!"
          cd android/app
          ls
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            build/outputs/apk/release/*.apk

